#include "BongoSprites.h"

#include "animations/body/bodyeartwitch.c"
#include "animations/body/standardbody1.c"
#include "animations/effects/left_click_effect.c"
#include "animations/effects/right_click_effect.c"
#include "animations/effects/sleepy1.c"
#include "animations/effects/sleepy2.c"
#include "animations/effects/sleepy3.c"
#include "animations/faces/blink_face.c"
#include "animations/faces/happy_face.c"
#include "animations/faces/sleepy_face.c"
#include "animations/faces/stock_face.c"
#include "animations/paws/leftpawdown.c"
#include "animations/paws/rightpawdown.c"
#include "animations/paws/twopawsup.c"
#include "animations/table/table1.c"
